services:
  - type: web
    name: santosh-kumbhkar
    env: node
    nodeVersion: 16.x
    buildCommand: |
      npm install
      cd portfolio-frontend
      npm install
      npm run build
      cd ..
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
    
        sync: false # This will allow you to set it securely through Render dashboard
